In [6]:
import scipy
import matplotlib.pyplot as plt

## Task1

In [7]:
from scipy.cluster.vq import kmeans, vq, whiten, kmeans2

student_scores =  [[80] , [78] , [55] , [60] , [62] ,
                    [59] , [48] , [49] , [51] , [54] ,
                    [72] , [95] , [78] , [54] , [50] ,
                    [61] , [57] , [56] , [65] , [53]]


## Task2

In [8]:
student_scores = whiten ( student_scores )
centroids ,_ = kmeans ( student_scores ,2)


## Task3

In [9]:
result,_ = vq( student_scores , centroids )
print(result)

[0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1]


<mark>Answer</mark>  
result is values which student_scores near centroids

## Task4

In [11]:
student_scores =  [[80] , [78] , [55] , [60] , [62] ,
                    [59] , [48] , [49] , [51] , [54] ,
                    [72] , [95] , [78] , [54] , [50] ,
                    [61] , [57] , [56] , [65] , [53]]
student_scores = whiten ( student_scores )
centroids ,_ = kmeans ( student_scores ,4)
result,_ = vq( student_scores , centroids )
print(result)

[0 0 1 2 2 2 1 1 1 1 0 3 0 1 1 2 2 1 2 1]


## Task5

In [14]:
student_scores = [[80 , 72] , [78 , 56] , [55 , 64] , [60 , 61] , [62 , 45] ,
[59 , 71] , [48 , 85] , [49 , 45] , [51 , 55] , [54 , 62] ,
[72 , 81] , [95 , 81] , [78 , 92] , [54 , 80] , [50 , 50] ,
[61 , 65] , [57 , 62] , [56 , 55] , [65 , 63] , [53 , 72]]
student_scores = whiten ( student_scores )
centroids ,_ = kmeans ( student_scores ,4)
result,_ = vq( student_scores , centroids )
print(result)

[2 2 1 1 0 1 3 0 0 1 2 2 2 3 0 1 1 0 1 3]


## Task6

In [17]:
import scipy.constants
print ("The PI is %.16f" %scipy.constants.pi)
print ("The speed of light is c = %.1F" %scipy.constants.c)
print ("The newton ’s gravity constant is G = %.1F" %scipy.constants.g)

The PI is 3.1415926535897931
The speed of light is c = 299792458.0
The newton ’s gravity constant is G = 9.8


## Task7

In [22]:
scipy.constants.find("gram")

['atomic mass unit-kilogram relationship',
 'electron volt-kilogram relationship',
 'hartree-kilogram relationship',
 'hertz-kilogram relationship',
 'inverse meter-kilogram relationship',
 'joule-kilogram relationship',
 'kelvin-kilogram relationship',
 'kilogram-atomic mass unit relationship',
 'kilogram-electron volt relationship',
 'kilogram-hartree relationship',
 'kilogram-hertz relationship',
 'kilogram-inverse meter relationship',
 'kilogram-joule relationship',
 'kilogram-kelvin relationship']

<mark>Answer</mark>  
Return list of physical_constant keys containing a given string.

## Task8

In [23]:
print ( scipy.constants.physical_constants ["atomic mass unit-kilogram relationship"])

(1.6605390666e-27, 'kg', 5e-37)


## Task9

In [25]:
print('Energy is {}' .format(56.5*scipy.constants.c**2))

Energy is 5.07796675986302e+18


## Task10

In [30]:

from scipy import stats
import numpy as np
x = np. array ([19 ,18 ,21 ,16 ,15 ,17 ,20 ,18])
print ( stats.tmin(x),stats.tmax(x),stats.tmean(x),stats.tvar(x) )


15 21 18.0 4.0


## Task13

In [31]:
print(stats.describe(x))


DescribeResult(nobs=8, minmax=(15, 21), mean=18.0, variance=4.0, skewness=0.0, kurtosis=-1.0)


## Task12

In [32]:
student_scores = [[80] , [78] , [55] , [60] , [62] ,
[59] , [48] , [49] , [51] , [54] ,
[72] , [95] , [78] , [54] , [50] ,
[61] , [57] , [56] , [65] , [53]]
print (stats.tmean(student_scores))
print (stats.tstd(student_scores))
print ((62 - stats.tmean(student_scores))/stats.tstd(
student_scores))

61.85
[12.55838994]
[0.01194421]


## Task13

In [36]:
mean = np.mean(student_scores)
std = stats.tstd(student_scores)
for i in student_scores:
    print('z is {}' .format((i-mean)/std))

z is [1.44524896]
z is [1.28599288]
z is [-0.54545209]
z is [-0.14731188]
z is [0.01194421]
z is [-0.22693992]
z is [-1.10284838]
z is [-1.02322034]
z is [-0.86396425]
z is [-0.62508013]
z is [0.80822462]
z is [2.63966959]
z is [1.28599288]
z is [-0.62508013]
z is [-0.9435923]
z is [-0.06768384]
z is [-0.386196]
z is [-0.46582404]
z is [0.25082833]
z is [-0.70470817]


61.85
